#!/bin/bash

# if first time run!
if [ ! -d "LinuxServerSetup" ]; then
        [[ $( which git ) ]] || {
                if [ -f /etc/os-release ]; then
                        # freedesktop.org and systemd
                        . /etc/os-release
                        OS=$NAME
                        OS_VER=$VERSION_ID
                else
                        # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
                        OS=$(uname -s)
                        OS_VER=$(uname -r)
                fi


                case $OS in
                        "Debian GNU/Linux"|"Ubuntu")
                                apt-get -qq install git
                                ;;
                        "CentOS Linux")
                                yum -y install git
                                ;;
                esac
        }
        git clone https://github.com/TirsvadCMS/LinuxServerSetup.git
        cd LinuxServerSetup
        git submodule init
        git submodule update
fi
cd LinuxServerSetup
bash setup/start.sh